#!/usr/bin/env bash
#Display username, user ID, and home directory of all users from /etc/passwd
while IFS=: read -r username _ userid _ _ home _; do
    echo "$username:$userid:$home"
done < /etc/passwd
