#!/usr/bin/env bash
#Display detailed information about each user from /etc/passwd in a descriptive sentence
while IFS=: read -r username password userid group_id user_id_info  home command_shell; do
echo "The user $username is part of the $group_id gang, lives in $home and rides $command_shell. $userid's place is protected by the passcode $password, more info about the user here: $user_id_info"; done < /etc/passwd
