#!/usr/bin/env bash
#Code writes 10 times "Best schoool" but in 9th echo it also adds "Hi"
i=1;
while ((i<10)); 
    do echo "Best School"
    if ((i==9));
        then echo "Hi" && echo "Best School"
    fi; 
((i++)); done
