#!/usr/bin/env bash
#Prints "Best School" 10 times, but says "good luck" at 4 and "bad luck" at 8
i=1;
while ((i<=10)); 
    do
        if ((i==8));
            then echo "bad luck"
        elif ((i==4));
            then echo "good luck"
        else echo "Best School"
        fi; 
((i++)); done
