#!/usr/bin/env bash
#Loops from 1 to 19, printing each number and a country-specific "bad luck" message for 4, 9, and 17
i=1;
while [[ $i -lt 20 ]]; do 
    echo "$i"
    case $i in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac 
    ((i++)) 
done
