#!/usr/bin/env bash
# Prints hours 1–12 and lists minutes 1–59 for each hour
i=1;
while ((i<=12)); do
    echo "Hour: $i"
    y=1;
    while ((y<=59)); do
        echo "$y"
        ((y++));
    done
    ((i++));
done
