#!/usr/bin/env bash
#Loops through all files in the current directory and prints each filename with digits and dashes removed
for item in *; do
    if [[ "$item" == *-* ]]; then
        echo "${item#*-}"
    else
        echo "$item"
    fi
done
