#!/usr/bin/env bash

PIDFILE="/var/run/my_process.pid"

case "$1" in
    start)
        if [[ -e "$PIDFILE" ]]; then
            echo "manage_my_process already running"
            exit 1
        fi
        echo "manage_my_process started"
        bash manage_my_process &
        echo $! > "$PIDFILE"
        ;;
    
    stop)
        if [[ ! -e "$PIDFILE" ]]; then
            echo "manage_my_process not running"
            exit 1
        fi
        kill -9 "$(cat "$PIDFILE")"
        rm -f "$PIDFILE"
        echo "manage_my_process stopped"
        ;;
    
    restart)
        if [[ -e "$PIDFILE" ]]; then
            kill -9 "$(cat "$PIDFILE")"
            rm -f "$PIDFILE"
        fi
        echo "manage_my_process restarted"
        bash manage_my_process &
        echo $! > "$PIDFILE"
        ;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
