#!/usr/bin/env bash
#This is hard script
if [[ -z "$1" ]]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi
if [[ $1 == "start" && ! -e "/var/run/my_process.pid" ]]; then
    echo "manage_my_process started"
    bash manage_my_process; echo $$ > "/var/run/my_process.pid" &
elif [[ $1 == "stop" ]]; then
    kill -9 "$(cat "/var/run/my_process.pid")"
    rm -f "/var/run/my_process.pid"
    echo 'manage_my_process stopped'
elif [[ $1 == "restart" &&  -e "/var/run/my_process.pid" ]]; then
    kill -9 "$(cat "/var/run/my_process.pid")"
    rm -f "/var/run/my_process.pid"
    echo "manage_my_process restarted"
    bash manage_my_process;echo $$ > "/var/run/my_process.pid" &
else
    exit 1
fi
