#!/usr/bin/env bash
#This is hard script

PID="/var/run/my_process.pid"

if [[ $1 == "start" && ! -e "$PID" ]]; then
    echo "manage_my_process started"
    bash manage_my_process &
    echo $! > "$PID"

elif [[ $1 == "stop" ]]; then
    kill -9 "$(cat "$PID")"
    rm -f "$PID"
    echo "manage_my_process stopped"

elif [[ $1 == "restart" && -e "$PID" ]]; then
    kill -9 "$(cat "$PID")"
    rm -f "$PID"
    echo "manage_my_process restarted"
    bash manage_my_process &
    echo $! > "$PID"

else
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi
